apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  labels:
    app: php-app
  namespace: default
spec:
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: php-app
  replicas: 1
  strategy: 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php-app
          image: "gcr.io/gcp-training-final-task/php-app:0.0.1"
          imagePullPolicy: Always
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - name: http
              containerPort: 80
            - name: health
              containerPort: 81
          