apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  labels:
    app: php-app
  namespace: default
spec:
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: php-app
  replicas: 1
  strategy: 
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: php-app
    spec:
      # serviceAccountName: php-db-account
      containers:
        - name: php-app
          image: "gcr.io/gcp-training-final-task/php-app:0.0.1"
          imagePullPolicy: Always
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: php-db-secret
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: php-db-secret
                key: password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: php-db-secret
                key: database
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command:
            - "/cloud_sql_proxy"
            - "-ip_address_types=PRIVATE"
            - "-instances=gcp-training-final-task:europe-central2:php-db=tcp:3306"
            - "-credential_file=/secrets/service_account.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: sa-secret-volume
              mountPath: /secrets/
              readOnly: true
      volumes:
      - name: sa-secret-volume
        secret:
          secretName: php-db-account-secret
        
          